# Generated by Django 3.2.11 on 2022-02-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ListItem',
        ),
    ]
