# Generated by Django 3.2.11 on 2022-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0002_rename_list_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
